name: petrecycler
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'



#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


  #utility packages
  smooth_page_indicator: ^1.1.0
  lottie: ^3.0.0
  shimmer: ^3.0.0
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  flutter_native_splash: ^2.3.10
  carousel_slider: ^4.2.1
  curved_navigation_bar: ^1.0.3
  connectivity_plus: ^6.0.1
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.2.0

  #icons
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8

  #fonts
  google_fonts: ^6.1.0

  #state management
  get: ^4.6.6
  get_storage: ^2.1.1

  #product specific
  fl_chart: ^0.67.0

  #firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.14.0
  firebase_messaging: ^14.8.1
  firebase_analytics: ^10.10.1
  firebase_app_check: ^0.2.2+2

  #google
  google_sign_in: ^6.2.1
  google_maps_flutter: ^2.2.8

  #--------------- ./ PACKAGES END ------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1


flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/logos/recycle.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/animations/
    - assets/banners/
    - assets/icons/
    - assets/images/
    - assets/images/profile/
    - assets/logos/
   


  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
 