// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjgNmZBHf9qSb6g1LPnaez4YIl3HVvQFQ',
    appId: '1:1011401755857:android:feac07aa1100ed3ba709f0',
    messagingSenderId: '1011401755857',
    projectId: 'petrecycler-d8be8',
    storageBucket: 'petrecycler-d8be8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIolNtrxfq7zLsyzXNvcXO4FHf3k1bFIA',
    appId: '1:1011401755857:ios:614ac0441a36efc1a709f0',
    messagingSenderId: '1011401755857',
    projectId: 'petrecycler-d8be8',
    storageBucket: 'petrecycler-d8be8.appspot.com',
    androidClientId: '1011401755857-vdlo4efv1ru1s3095pejk7nth5740q2n.apps.googleusercontent.com',
    iosClientId: '1011401755857-ajr103i5imji24ol5m5onhitefbjgjgv.apps.googleusercontent.com',
    iosBundleId: 'com.example.petrecycler',
  );
}
